#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/prezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/prezto/init.zsh"
else
  echo "Prezto not found: ${ZDOTDIR:-$HOME}/prezto/init.zsh"
fi

# Customize to your needs...

setopt nosharehistory

# jk: custom edits under this line
# aliasses
alias qemu-conf="../../../configure --python=/usr/bin/python2 --target-list=x86_64-softmmu --audio-drv-list=pa --enable-kvm --enable-vhost-net"
alias grep-grey="GREP_COLOR='1;30' grep --color=always"
alias grep-red="GREP_COLOR='1;31' grep --color=always"
alias grep-green="GREP_COLOR='1;32' grep --color=always"
alias grep-yellow="GREP_COLOR='1;33' grep --color=always"
alias grep-blue="GREP_COLOR='1;34' grep --color=always"
alias grep-magenta="GREP_COLOR='1;35' grep --color=always"
alias grep-cyan="GREP_COLOR='1;36' grep --color=always"
alias grep-white="GREP_COLOR='1;37' grep --color=always"

alias pgr="ps aux | grep -v grep | grep -e"

# util
function nvm {
  unset -f $funcstack[1]
  export NVM_DIR=~/.nvm && source $(brew --prefix nvm)/nvm.sh
  # . /usr/share/nvm/init-nvm.sh
  nvm "$@"
}


# homebrew stuff
export HOMEBREW_NO_INSTALL_CLEANUP
export HOMEBREW_NO_AUTO_UPDATE

# exports
# fix for linux based osses wanted LC_ALL set
export LC_ALL=$LANG

# config
alias nano=/usr/bin/vim
alias really_nano=/usr/bin/nano
alias watch="watch --color"

# sudoedit (osx compat)
if [[ "$(uname -s)" == "Darwin" ]]; then
  alias se="sudo -e"
  alias updatedb="sudo /usr/libexec/locate.updatedb"
elif [[ "$(uname -s)" == "Linux" ]]; then
  alias se=sudoedit
fi
export SUDOEDITOR=vim

export PATH="$HOME/.local/bin:$PATH"

# To customize prompt, run `p10k configure` or edit ~/.zhome/.p10k.zsh.
[[ ! -f ~/.zhome/.p10k.zsh ]] || source ~/.zhome/.p10k.zsh

export DOCKER_SCAN_SUGGEST=false
